version: '3'

services:
  contact_form_service__email_notification_task:
    depends_on:
      - kafka
    image: jhines2017/send-email-notification-worker:1.2.2-SNAPSHOT
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - engine.labels.node.type==contactformservice
    environment:
      - ZOOKEEPER_HOST
      - KAFKA_HOST
      - JHC_GMAIL_PASSWORD
      - JHC_GMAIL_ADDRESS