version: '3'

services:
  ui:
    depends_on:
      - contact_form_service__handle_contact_request_task
    image: jhines2017/jhines-consulting-blog-ui:0.25.3
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==blog-ui