version: '3.2'

services:
  ui:
    depends_on:
      - contact_form_service__contact_form_task
    image: jhines2017/jhinesconsulting-blog-ui:0.77.21
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - webroot:/usr/share/nginx/html
      - /dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/jhinesconsulting.com/fullchain.pem:/etc/letsencrypt/live/jhinesconsulting.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/jhinesconsulting.com/privkey.pem:/etc/letsencrypt/live/jhinesconsulting.com/privkey.pem
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - engine.labels.node.type==jhcui
#volumes:
#  webroot: