version: '3'

services:
  ui:
    depends_on:
      - contact_form_service__contact_form_task
    image: jhines2017/jhinesconsulting-blog-ui:0.41.10
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - engine.labels.node.type==ui