version: '3'

services:
  httpsourcetask:
    image: jhines2017/http-source-worker:10-1.3.1.RELEASE
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==contactformsubmissionservice
    ports:
      - "3000:3000"