version: '3'

services:
  contact_form_service__save_contact_to_db_task:
    depends_on:
      - mysql
    image: jhines2017/db-sink-worker:10-1.3.1.RELEASE
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==contactformservice
    environment:
      - DB_HOST
      - JHC_DB_USER
      - JHC_DB_PASS
      - CONTACT_REQUEST_OUTPUT_CHANNEL