version: '3'

services:
  blog:
    image: jhines2017/jhines-consulting-blog:0.8.0
    ports:
      - "3306:3306"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==512mb
volumes:
  db_data:
