version: '3'

services:
  blog:
    image: jhines2017/jhines-consulting-blog:0.13.3
    depends_on:
      - contactformsubmissiontask
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==512mb
  contactformsubmissiontask:
    image: jhines2017/mock-contact-form-submission-worker:1.0.0
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==512mb
volumes:
  db_data:
