version: '3'

services:
  httpsourcetask:
    depends_on:
      - kafka
    image: jhines2017/http-source-worker:10-1.3.1.RELEASE
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==contactformsubmissionservice
    environment:
      - ZOOKEEPER_HOST
      - KAFKA_HOST
    ports:
      - "3000:3000"
  zookeeper:
    image: wurstmeister/zookeeper
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==kafka
  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  db_data:
