version: '3'

services:
  contact_form_service__save_contact_to_db_task:
    depends_on:
      - mysql
    image: jhines2017/save-contact-to-db-worker:1.1.0-SNAPSHOT
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==contactformservice
    environment:
      - DB_HOST
      - JHC_DB_USER
      - JHC_DB_PASS
      - ZOOKEEPER_HOST
      - KAFKA_HOST