version: '3'

services:
  list_projects_service__list_projects_task:
    depends_on:
      - projectsdb
    image: jhines2017/list-projects-request-handler-worker:1.4.0.RELEASE
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - engine.labels.node.type==listprojectsservice
    environment:
      - PROJECTS_DB_HOST
      - PROJECTS_DB_PORT
      - JHC_DB_USER
      - JHC_DB_PASS
    ports:
      - ${LIST_PROJECTS_WORKER_PORT}:${LIST_PROJECTS_WORKER_PORT}