version: '3'

services:
  contact_form_service__handle_contact_request_task:
    depends_on:
      - kafka
    image: jhines2017/contact-request-handler-worker:1.6.0-SNAPSHOT
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==contactrequesthandler
    environment:
      - ZOOKEEPER_HOST
      - KAFKA_HOST
    ports:
      - "3000:3000"