version: '3'

services:
  create_project_service__create_project_task:
    depends_on:
      - kafka
    image: jhines2017/create-project-request-handler-worker:1.0.0-SNAPSHOT
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - engine.labels.node.type==createprojectservice
    environment:
      - ZOOKEEPER_HOST
      - KAFKA_HOST
    ports:
      - "3001:3001"