version: '3'

services:
  create_project_service__save_project_to_db_task:
    depends_on:
      - projectsdb
    image: jhines2017/save-project-to-db-worker:1.0.1.RELEASE
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - engine.labels.node.type==jhccreateprojectservice
    environment:
      - ZOOKEEPER_HOST
      - KAFKA_HOST
      - PROJECTS_DB_HOST
      - PROJECTS_DB_NAME
      - JHC_DB_USER
      - JHC_DB_PASS