version: '3'

services:
  contact_form_service__handle_form_submission_task:
    depends_on:
      - dbsinktask
    image: jhines2017/contact-form-submission-request-handler-worker:1.0.0-SNAPSHOT
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==formhandler
    environment:
      - ZOOKEEPER_HOST
      - KAFKA_HOST
    ports:
      - "3000:3000"