#!/bin/bash

echo "=======> setting env variables for manager node"

{
    echo "DB_HOST=$1"
    echo "KAFKA_HOST=$2"
    echo "ZOOKEEPER_HOST=$3"
    echo "OKHTTP_CLIENT_TIMEOUT_SECONDS=$4"
    echo "OCCASION_EXPORT_STARTING_PAGE_NUM=$5"
    echo "IF_OCCASION_EXPORT_URL=$6"
    echo "IF_DB_PASSWORD=$7"
    echo "IF_DB_PORT=$8"
    echo "IF_DB_ROOT_PASS=$9"
    echo "IF_DB_USERNAME=${10}"
    echo "IF_OCCASION_CREDS=${11}"
    echo "DOCKER_HUB_USER=${12}"
    echo "DOCKER_HUB_PASSWORD=${13}"
    echo "DIGITALOCEAN_ACCESS_TOKEN=${14}"
    echo "MAX_SAVE_ORDER_TO_DB_WORKER_COUNT=${15}"
    echo "RECONCILE=${16}"
    echo "SAVE_ORDER_TO_DB_WORKER_NODE_COUNT=${17}"
    echo "ORDER_IDS_FILE=${18}"
    echo "ENV=${19}"
    echo "NUM_SAVE_ORDER_TO_DB_WORKERS=${20}"
    echo "PAGE_SIZE=${21}"
    echo "ACCESS_KEY_AWS=${22}"
    echo "SECRET_KEY_AWS=${23}"
    echo "NUM_ORDERS=${24}"
    echo "NUM_OCCURRENCES=${25}"
    echo "NUM_CUSTOMERS=${26}"
    echo "NUM_QUESTIONS=${27}"
    echo "NUM_ANSWERS=${28}"
    echo "EXPORT_FROM_FILE=${29}"
} | sudo tee -a /etc/environment > /dev/null
