version: '3.7'

services:
  contact_form_service__contact_form_task:
    depends_on:
      - kafka
    image: jhines2017/contact-form-worker:1.14.0.RELEASE
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - engine.labels.node.type==jhccontactformservice
    environment:
      - ZOOKEEPER_HOST
      - KAFKA_HOST
      - KEYSTORE_PASSWORD
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host