version: '3.7'

services:
  contact_form_service__contact_form_task:
    depends_on:
      - kafka
    image: jhines2017/contact-form-worker:1.14.0.RELEASE
    volumes:
      - /docker-volumes/etc/letsencrypt/live/contacts.jhinesconsulting.com/keystore.p12:/etc/letsencrypt/live/contacts.jhinesconsulting.com/keystore.p12
      - /dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker/letsencrypt-docker-nginx/src/production/production-site:/data/letsencrypt
      - /docker-volumes/etc/letsencrypt/live/contacts.jhinesconsulting.com/fullchain.pem:/etc/letsencrypt/live/contacts.jhinesconsulting.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/contacts.jhinesconsulting.com/privkey.pem:/etc/letsencrypt/live/contacts.jhinesconsulting.com/privkey.pem
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - engine.labels.node.type==jhccontactformservice
    environment:
      - ZOOKEEPER_HOST
      - KAFKA_HOST
      - KEYSTORE_PASSWORD
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8443
        published: 443
        protocol: tcp
        mode: host