version: '3.7'

services:
  contact_form_service__save_contact_to_db_task:
    depends_on:
      - contactsdb
    image: jhines2017/save-contact-to-db-worker:1.14.0.RELEASE
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - engine.labels.node.type==jhccontactformservice
    environment:
      - CONTACTS_DB_HOST
      - CONTACTS_DB_NAME
      - JHC_DB_USER
      - JHC_DB_PASS
      - ZOOKEEPER_HOST
      - KAFKA_HOST