version: '3'

services:
  create_project_service__save_project_to_db_task:
    depends_on:
      - mysql
    image: jhines2017/save-project-to-db-worker:10-1.3.1.RELEASE
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - engine.labels.node.type==createprojectservice