version: '3'

services:
  logsinkservice:
    depends_on:
      - kafka
    image: jhines2017/log-sink-service:10-1.3.1.RELEASE
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - engine.labels.node.type==contactformservice
    environment:
      - LOGGING_INPUT_CHANNEL